### ISSUE TITLE
Build fails with m2c: Permission denied in v2.9.7

### ISSUE THREAD

**Issue by khsa1** [times-software/OCEAN#279]
Compilation is failing with:

```
m2c    -o ../SCREEN/src/ocean_sphericalharmonics.o ../SCREEN/src/ocean_sphericalharmonics.mod

make[1]: execvp: m2c: Permission denied
```

This seems to be caused by:

https://github.com/times-software/OCEAN/blob/a4398d6d8883d133a9139e2ac9e322c18fa7838f/SCREEN/src/makefile#L27

When I remove the line build completes successfully.

**Comment by jtv3** [comment]
Thanks. Removing that line is fine for end users. I you are updating source code you might need to make clean each time.

I was having trouble with the intersection of 1) convincing make to honor the fact that fortran compilation results in both object and module files and 2) gfortran doesn't touch the mod file if it wasn't changed even if the object file was. I need to re-do the make file structure. 

I'll update here when I've changed things around

**Comment by jtv3** [comment]
Hoping this is fixed
