### ISSUE TITLE
Run OCEAN on charged system

### ISSUE THREAD

**Issue by KeweiZhao** [times-software/OCEAN#326]
Hello,

I'm wondering if it's possible to apply OCEAN to charged systems, e.g. molecular transition metal complexes. In QE there is an option in pw.x, "tot_charge", which set the total charge of the system, and a compensating jellium background is inserted to to make the cell neutral. Is there any way to parse this keyword to OCEAN? 

I also see in the "O2-mol" example, there is a keyword "nelectron", which is not in the manual. Will it work for this purpose?

Thanks,
Kewei Zhao

**Comment by jtv3** [comment]
The input parameter you are looking for is `structure.charge` . The flag nelectron is deprecated and should have absolutely no effect (but still needs to be cleaned out). Give it a try and let me know if it has the expected effect on the inputs for pw.x
